---
vars:
    apic_info: &apic_info
      host: "{{inventory_hostname}}"
      username: "{{ lookup("env", "ANSIBLE_NET_USERNAME") }}"
      password: "{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}"
      validate_certs: "false"
