---
vars:
  apic_info: &apic_info
    host: "{{inventory_hostname}}"
    username: "{{ lookup("env", "ANSIBLE_NET_USERNAME") }}"
    password: "{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}"
    validate_certs: "false" 
      
  tenant:
  - tenantName: BIGM
    
  app_profile:
  - app_pr: app_dmz	

  vrfs:
  - tenantName: BIGM
    vrfName: vrf-01
