- name: Create ACI objects from CSV
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: reading the csv file
      read_csv:
        path: aci_vars.csv
      delegate_to: localhost
      register: aci_objects

    - name: Create End Point Groups "{{ item.epg | trim }}" with pause between each
      include_tasks: epg_create_block.yaml
      loop: "{{ aci_objects.list }}"
      loop_control:
        label: "{{ item.tenant | trim }}-{{ item.bd | trim }}-{{ item.epg | trim }}-{{ item.app_profile | trim }}"