- name: Create ACI objects from CSV
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: reading the csv file
      read_csv:
       path: aci_vars.csv
      delegate_to: localhost
      register: aci_objects

    - name: Create Physical Domain
      aci_domain:
        host: "{{ apic_url }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        validate_certs: no
        domain: "{{ aci_objects.list[0].phys_domain | trim }}"
        domain_type: phys
        #description: "{{ aci_objects.list[0].phys_domain_desc | trim }}"
        #vlan_pool: "{{ aci_objects.list[0].vlan_pool | trim }}"
        state: present
      delegate_to: localhost
