- name: Create ACI objects from CSV
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: reading the csv file
      read_csv:
        path: 8_aep_to_epg.csv
      delegate_to: localhost
      register: aci_objects

    - name: Creating AEP "{{ item.aep | trim }}" to Domain "{{ item.domain | trim }}" mapping 
      include_tasks: 8_aep_to_domain_block.yaml
      loop: "{{ aci_objects.list }}"
      loop_control:
        label: "{{ item.aep | trim }}{{ item.domain | trim }}"