- name: Create ACI objects from CSV
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: reading the csv file
      read_csv:
       path: aci_vars.csv
      delegate_to: localhost
      register: aci_objects

    - name: AEP to Domain binding 
      aci_aep_to_domain:
        host: "{{ apic_url }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        validate_certs: no
        aep: "{{ aci_objects.list[0].aep | trim }}"
        domain: "{{ aci_objects.list[0].phys_domain | trim }}"
        domain_type: phys
        state: present
      delegate_to: localhost
