---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new leaf interface profile
    aci_interface_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_interface_profile: "{{apic_leaf_profile}}"
      description: created by Ansible
      validate_certs: no
      state: present
