---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no  

  tasks: 
  - name: Add a new tenant
    aci_tenant:
      <<: *apic_info
      tenant: "{{tenant}}"
      description: Tenant created by Ansible Tower
      state: present
