# Add Tenant 
- name: ACI Configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new tenant "{{tenant}}"
    aci_tenant:
      tenant: "{{tenant}}"
      validate_certs: no
      description: Tenant created by Ansible
      state: present
    delegate_to: localhost
