# Create VRF
---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new VRF "{{apic_vrf}}" to a tenant
    aci_vrf:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vrf: "{{apic_vrf}}"
      tenant: "{{apic_tenant}}"
      validate_certs: no
      descr: VRF creaded by Ansible
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
