---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      use_proxy: no
      path: /api/mo/.json
      method: post
      
    EPG_Constructs:
      - tenant: Outer-DMZ
        app_pr: app-DMZ
        bd: VLAN100
        epg: VLAN100
        EPG_Des: EPG for VLAN100
        tag: VLAN100 
        ph-dom: phd-dmz
      
  tasks:	  
  - name: Create EPGs
    aci_rest:
      <<: *apic_info
      content:
        {
          "fvAEPg": {
            "attributes": {
              "annotation": "",
              "descr": "{{item.EPG_Des}}",
              "dn": "uni/tn-{{item.tenant}}/ap-{{item.app_pr}}/epg-{{item.epg}}",
              "exceptionTag": "{{item.tag}}",
              "floodOnEncap": "disabled",
              "fwdCtrl": "",
              "hasMcastSource": "no",
              "isAttrBasedEPg": "no",
              "matchT": "AtleastOne",
              "name": "{{item.epg}}",
              "nameAlias": "{{item.tag}}",
              "pcEnfPref": "unenforced",
              "prefGrMemb": "include",
              "prio": "unspecified",
              "shutdown": "no"
            },
            "children": [
              {
                "fvRsDomAtt": {
                  "attributes": {
                    "annotation": "",
                    "bindingType": "none",
                    "classPref": "encap",
                    "delimiter": "",
                    "encap": "unknown",
                    "encapMode": "auto",
                    "epgCos": "Cos0",
                    "epgCosPref": "disabled",
                    "instrImedcy": "lazy",
                    "lagPolicyName": "",
                    "netflowDir": "both",
                    "netflowPref": "disabled",
                    "numPorts": "0",
                    "portAllocation": "none",
                    "primaryEncap": "unknown",
                    "primaryEncapInner": "unknown",
                    "resImedcy": "lazy",
                    "secondaryEncapInner": "unknown",
                    "switchingMode": "native",
                    "tDn": "uni/phys-{{item.ph-dom}}"
                  }
                }
              },
              {
                "tagInst": {
                  "attributes": {
                    "annotation": "",
                    "name": "{{item.tag}}",
                    "nameAlias": ""
                  }
                }
              },
              {
                "fvRsCustQosPol": {
                  "attributes": {
                    "annotation": "",
                    "tnQosCustomPolName": ""
                  }
                }
              },
              {
                "fvRsBd": {
                  "attributes": {
                    "annotation": "",
                    "tnFvBDName": "{{item.bd}}"
                  }
                }
              }
            ]
          }
        }                  
    delegate_to: localhost 
    with_items:
      -	"{{EPG_Constructs}}"
