# Add Application Profile 
---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      
    app_profile:
    - app_pr: app-DMZ
      tenant: Outer-DMZ

  tasks: 
  - name: Add a new AP "{{apic_ap}}"
    aci_ap:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{item.tenant}}"
      ap: "{{item.app_pr}}"
      description: AP creaded by Ansible
      state: present
    with_items:
      - "{{app_profile}}"
    
