---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      use_proxy: no
      path: /api/mo/.json
      method: post
      
    BD_Constructs:
    - tenant: Outer-DMZ
      vrf: Outer-VRF
      BD: VLAN100
      BD_Description: BD for VLAN10
      tag: VLAN100
    - tenant: Outer-DMZ
      vrf: Outer-VRF
      BD: VLAN200
      BD_Description: BD for VLAN20
      tag: VLAN200
    - tenant: Outer-DMZ
      vrf: Outer-VRF
      BD: VLAN300   
      BD_Description: BD for VLAN30
      tag: VLAN300

  tasks:	  
  - name: Create BD
    aci_rest:
      <<: *apic_info
      content:
        {
          "fvBD": {
            "attributes": {
              "descr": "{{item.BD_Description}}",
              "dn": "uni/tn-{{item.tenant}}/BD-{{item.BD}}",
              "mac": "00:22:BD:F8:19:FF", 
              "name": "{{item.BD}}",
              "rn": "BD-{{item.BD}}",
              "nameAlias": "{{item.tag}}",
              "arpFlood": "yes",
              "unicastRoute": "no",
              "unkMacUcastAct": "flood",
              "unkMcastAct": "flood",
              "multiDstPktAct": "bd-flood",
              "status": "created"
            },
            "children": [
              {
                "tagInst": {
                  "attributes": {
                    "annotation": "",
                    "name": "{{item.tag}}",
                    "nameAlias": ""
                  }
                }  
              },
              {
                "fvRsCtx": {
                  "attributes": {
                    "tnFvCtxName": "{{item.vrf}}",
                    "status": "created,modified"
                  },
                  "children": [
                    
                  ]
                }
              }
            ]
          }
        }
    delegate_to: localhost    
    with_items:
      - "{{BD_Constructs}}"  
