---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new AEP "{{apic_aep}}" 
    aci_aep:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      aep: "{{apic_aep}}"
      description: created by ansible
      validate_certs: no
      state: present
