---
- name: ACI Configuration
  hosts: APIC-Group
  connection: local
  gather_facts: no

  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      
    BDs:
    - tenant: Outer-DMZ
      vrf: Outer-VRF
      BD: 
      - VLAN10
      - VLAN20
      - VLAN30

  tasks: 
  - name: Add Bridge Domain "{{item.BD}}"
    aci_bd:
      <<: *apic_info
      state: present
      tenant: "{{item.tenant}}"
      bd: "{{item.BD}}"
      vrf: "{{item.vrf}}"
    with_items:
       - "{{BDs}}"

