---
- name: Read data from CSV file
  hosts: all
  gather_facts: no
  tasks:
    - name: reading the csv file
      read_csv:
       path: data.csv
      delegate_to: localhost
      register: data_list

    - name: display CSV data
      debug:
       msg: "{{ data_list.list }}"

    - name: print dictionaries
      debug:
        msg: "{{ item.tenant }}"
      loop: "{{ data_list.list }}"

