# playbook.yml
- name: Use CSV in Ansible Tower and AWX
  hosts: localhost
  gather_facts: no
  vars:
    csv_file_path: "data.csv"

  - name: create users from csv file
    hosts: all
    tasks:
    - name: reading the csv file
      read_csv:
        csv_file_path: data.csv
      register: user_list
      delegate_to: localhost

    - name: display user_list data
      debug:
        var: user_list.list