---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks:    
  - name: Adding switch policy leaf profile selector associated Node Block range
    aci_switch_leaf_selector:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_profile: SW_Leaf_101_102
      leaf: node_101_102
      leaf_node_blk: L_101_102
      from: 101
      to: 102
      validate_certs: no
      state: present
