---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Associate interface selector profile to switch policy leaf profile 
    aci_interface_selector_to_switch_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_profile: SW_Leaf_101_102
      interface_selector: "{{apic_leaf_profile}}"
      validate_certs: no
      state: present 
