---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Create a leaf access port policy group
    aci_interface_policy_leaf_policy_group:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      lag_type: leaf
      policy_group: Access_Port_Policy
      link_level_policy: port_speed
      cdp_policy: enable_cdp
      description: created by Ansible
      validate_certs: no
      state: present 
