---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks: 
  - name: Associate policy group to interface selector 
    aci_access_port_to_interface_policy_leaf_profile:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      leaf_interface_profile: "{{apic_leaf_profile}}"
      access_port_selector: Port_Selector
      policy_group: Access_Port_Policy
      description: created by Ansible
      validate_certs: no
      state: present 
