---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  tasks:  
  - name: Static path binding for given EPG 
    aci_static_binding_to_epg:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{apic_tenant}}"
      ap: "{{apic_ap}}"
      epg: "{{apic_epg_01}}"  
      encap_id: 3001
      deploy_immediacy: lazy
      interface_mode: untagged
      interface_type: switch_port
      pod_id: 1
      leafs: 101
      interface: '1/31'  
      validate_certs: no
      state: present 
