---
- name: Configure Cisco ACI Tenant
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - aci_vars.yml

  tasks:
    - name: Create ACI tenant
      cisco.aci.aci_tenant:
        host: "{{ aci_url }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        tenant: "{{ tenant_name }}"
        state: present
        validate_certs: no
