- name: Configure Cisco ACI Tenant
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
   - my_variables.yml

  tasks:
    - name: reading the csv file
      read_csv:
       path: data.csv
      delegate_to: localhost
      register: data_list

    - name: display CSV data
      debug:
       msg: "{{ data_list.list }}"

    - name: print dictionaries
      debug:
        msg: "{{ item.tenant }}"
      loop: "{{ data_list.list }}"

    - name: Add a new tenant
      aci_tenant:
        host: "{{aci_url}}"
        username: "{{aci_username}}"
        password: "{{aci_password}}"
        tenant: "{{item.tenant}}"
        description: Tenant created by Ansible
        state: present
        validate_certs: no
      loop: "{{data_list.list}}"
      
    - name: Add a new Application Profile
      aci_ap:
        host: "{{aci_url}}"
        username: "{{aci_username}}"
        password: "{{aci_password}}"
        tenant: "{{item.tenant}}"
        ap: "{{item.app_pr}}"
        description: AP Created by Ansible
        monitoring_policy: default
        state: present
        validate_certs: no
      loop: "{{data_list.list}}"

