---
- name: Configure Cisco ACI Tenant
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new tenant
    aci_tenant:
      host : "{{ aci_url }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ Tenant }}"
      description: Tenant created by Ansible
      state: present
      validate_certs: no