---
- name: Configure Cisco ACI Tenant
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
  - name: Add a new tenant
    aci_tenant:
      host : "{{ aci_url }}"
      tenant: "{{tenant}}"
      description: Tenant created by Ansible
      state: present
      validate_certs: no