---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      
  tasks: 
  - name: Add a new tenant
    aci_tenant:
      <<: *apic_info
      tenant: "{{tenant}}"
      description: {{description}}
      state: present

          
