# Add Application Profile 
---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"

  tasks: 
  - name: Add a new AP "{{apic_ap}}"
    aci_ap:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      description: "{{description}}"
      state: present

    
