---
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no

  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"

  tasks: 
    - name: Add a new VRF "{{vrf}}" to a tenant
      aci_vrf:
        <<: *apic_info
        vrf: "{{vrf}}"
        tenant: "{{tenant}}"
        descr: "{{description}}"
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present

