--- 
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      use_proxy: no
      path: /api/mo/.json
      method: post   
      
  tasks:	  
  - name: Create EPGs
    aci_rest:
      <<: *apic_info
      content:
        fvAEPg:
          attributes:
            dn: uni/tn-{{item.tenant}}/ap-{{item.app-pr}}/epg-{{item.epg}}
            name: "{{item.epg}}"
            rn: epg-{{item.epg}}
            status: created
          children:
          - fvRsBd:
              attributes:
                tnFvBDName: "{{item.bd}}"
                status: created,modified
              children: []	  
    with_itemas:
      - "{{EPG_Constructs}}"
