--- 
- name: ACI Configuration
  hosts: aci
  connection: local
  gather_facts: no
  
  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      use_proxy: no
      path: /api/mo/.json
      method: post   
      
  tasks:	  
  - name: Create EPGs
    aci_rest:
      <<: *apic_info
      content:
        totalCount: '1'
        imdata:
        - fvAEPg:
            attributes:
              annotation: ''
              descr: "{{item.des}}"
              dn: uni/tn-{{item.tenant}}/ap-{{item.app-pr}}/epg-{{item.epg}}
              exceptionTag: "{{item.tag}}"
              floodOnEncap: disabled
              fwdCtrl: ''
              hasMcastSource: 'no'
              isAttrBasedEPg: 'no'
              matchT: AtleastOne
              name: "{{item.epg}}"
              nameAlias: "{{item.tag}}"
              pcEnfPref: unenforced
              prefGrMemb: include
              prio: unspecified
              shutdown: 'no'
            children:
            - fvRsDomAtt:
                attributes:
                  annotation: ''
                  bindingType: none
                  classPref: encap
                  delimiter: ''
                  encap: unknown
                  encapMode: auto
                  epgCos: Cos0
                  epgCosPref: disabled
                  instrImedcy: lazy
                  lagPolicyName: ''
                  netflowDir: both
                  netflowPref: disabled
                  numPorts: '0'
                  portAllocation: none
                  primaryEncap: unknown
                  primaryEncapInner: unknown
                  resImedcy: lazy
                  secondaryEncapInner: unknown
                  switchingMode: native
                  tDn: uni/phys-{{item.ph_dom}}
            - tagInst:
                attributes:
                  annotation: ''
                  name: "{{item.tag}}"
                  nameAlias: ''
            - fvRsCustQosPol:
                attributes:
                  annotation: ''
                  tnQosCustomPolName: ''
            - fvRsBd:
                attributes:
                  annotation: ''
                  tnFvBDName: "{{item.bd}}"
    with_items:
      - tenant: ABC
        app_pr: app_ABC
        bd: bd_VLAN10
        epg: epg_VLAN10
        des: EPG_VLAN10
        tag: VLAN10
        ph_dom: phd_dmz
