---
- name: ACI Configuration
  hosts: APIC-Group
  connection: local
  gather_facts: no

  vars:
    apic_info:        &apic_info
      host:           '{{ inventory_hostname }}'
      username:       '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password:       '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: "false"
      
    tenant:
    - tenantName: BIGM
      
tasks: 
  - name: Add a new tenant "{{tenant}}"
    aci_tenant:
      <<: *apic_info
      tenant: "{{item.tenantName}}"
      description: Tenant created by Ansible
      state: present
    delegate_to: localhost
    with_items:
      - "{{tenant}}"
