---
- name: ACI Configuration
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    apic_info: &apic_info
      host: "{{inventory_hostname}}"
      username: "{{ lookup("env", "ANSIBLE_NET_USERNAME") }}"
      password: "{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}"
      validate_certs: "false" 
 
    tenant:
    - tenantName: BIGM
    
    app_profile:
    - app_pr: app_dmz	

    vrfs:
    - tenantName: BIGM
      vrfName: vrf-01
      
    intf_policies:
    - "ESX_Hosts"
    - "Linux_Hosts"
    - "Windows_Hosts"

    ifPolicyLeafProfileNames:
    - Leaf_101
    - Leaf_102
    - Leafs_101_and_102

    interfaceSelectors:
    - ifPolicyLeafProfileName: Leafs_101_and_102
      intf_policy: Linux_Hosts
      fromCard: '1'
      fromPort: '1'
      toCard: '1'
      toPort: '48'

    swPolicyLeafProfiles:
    - swPolicyLeafProfileName: Leaf_101
      leafName: Leaf-101
      leafId: '101'
    - swPolicyLeafProfileName: Leaf_102
      leafName: Leaf-102
      leafId: '102'
    - swPolicyLeafProfileName: Leafs_101_and_102
      leafName: Leaf-101
      leafId: '101'
    - swPolicyLeafProfileName: Leafs_101_and_102
      leafName: Leaf-102
      leafId: '102'

    bridgeDomains:
    - bdName: 192.168.100.0_24
      tenantName: BIGM
      vrfName: vrf-01
    - bdName: 192.168.101.0_24
      tenantName: BIGM
      vrfName: vrf-01

    bdSubnets:
    - bdName: 192.168.100.0_24
      tenantName: BIGM
      gwAddress: 192.168.100.1
      mask: 24
    - bdName: 192.168.101.0_24
      tenantName: BIGM
      gwAddress: 192.168.101.1
      mask: 24

    appProfiles:
    - apName: AProfile
      tenantName: BIGM

    epgs:
    - epgName: WebServers
      tenantName: BIGM
      apName: AProfile
      bdName: 192.168.100.0_24
    - epgName: DbServers
      tenantName: BIGM
      apName: AProfile
      bdName: 192.168.101.0_24

  tasks: 
  - name: Add a new tenant "{{tenant}}"
    aci_tenant:
      <<: *apic_info
      tenant: "{{tenant}}"
      description: Tenant created by Ansible
      state: present
    delegate_to: localhost
 
  - name: Add a new AP "{{app_pr}}"
    aci_ap:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      description: AP creaded by Ansible
      state: present

  - name: Add a new VRF "{{apic_vrf}}" to a tenant
    aci_vrf:
      <<: *apic_info
      vrf: "{{apic_vrf}}"
      tenant: "{{tenant}}"
      descr: VRF creaded by Ansible
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present

  - name: Add Bridge Domain "{{item}}"
    aci_bd:
      <<: *apic_info
      validate_certs: false
      state: present
      tenant: "{{tenant}}"
      bd: "{{item}}"
      vrf: "{{apic_vrf}}"
    with_items:
       - "{{apic_bd00}}"
       - "{{apic_bd01}}"
       - "{{apic_bd02}}"
    
  - name: Add a new EPG "{{apic_epg_01}}"
    aci_epg:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      epg: "{{apic_epg_01}}"
      description: Web EPG creaded by Ansible
      bd: "{{apic_bd00}}"
      preferred_group: yes
      state: present
    delegate_to: localhost
 
  - name: Add a new EPG "{{apic_epg_02}}"
    aci_epg:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      epg: "{{apic_epg_02}}"
      description: Web EPG creaded by Ansible
      bd: "{{apic_bd02}}"
      preferred_group: yes
      state: present
    delegate_to: localhost 

  - name: Add a new contract "{{apic_contract}}"
    aci_contract:
      <<: *apic_info
      tenant: "{{tenant}}"
      contract: "{{apic_contract}}"
      state: present

  - name: Add a new physical domain "{{apic_domain}}"
    aci_domain:
      <<: *apic_info
      domain: "{{apic_domain}}"
      domain_type: phys
      state: present       

  - name: Add a new AEP "{{apic_aep}}" 
    aci_aep:
      <<: *apic_info
      aep: "{{apic_aep}}"
      description: created by ansible
      state: present 

  - name: Add AEP to domain binding 
    aci_aep_to_domain:
      <<: *apic_info
      aep: "{{apic_aep}}"
      domain: "{{apic_domain}}"
      domain_type: phys
      state: present       
  
  - name: Add a physical domain to EPG
    aci_epg_to_domain:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      epg: "{{apic_epg_01}}"
      domain: "{{apic_domain}}"
      domain_type: phys
      state: present    

  - name: Add subnet in "{{apic_bd00}}"
    aci_bd_subnet:
      <<: *apic_info
      tenant: "{{tenant}}"
      bd: "{{apic_bd00}}"
      subnet_name: "{{apic_subnet1}}"
      gateway: "{{apic_subnet1_gw}}"
      mask: "{{apic_subnet1_mask}}"      
      scope: "public"

  - name: Add a new leaf interface profile
    aci_interface_policy_leaf_profile:
      <<: *apic_info
      leaf_interface_profile: "{{item}}"
      description: created by Ansible
      state: present 
    with_items:
      "{{ifPolicyLeafProfileNames}}"  
    loop_control:
      pause: .5    

  - name: Create interface selector and port block assign
    aci_access_port_to_interface_policy_leaf_profile:
      <<: *apic_info
      leaf_interface_profile: "{{apic_leaf_profile}}"
      access_port_selector: Port_Selector
      leaf_port_blk: Eth_Port_blk
      from_port: 41
      to_port: 46
      description: created by Ansible
      state: present   

  - name: Create a leaf access port policy group
    aci_interface_policy_leaf_policy_group:
      <<: *apic_info
      lag_type: leaf
      policy_group: Access_Port_Policy
      link_level_policy: port_speed
      cdp_policy: disable_cdp
      aep: "{{apic_aep}}"
      description: created by Ansible
      state: present      

  - name: Associate policy group to interface selector 
    aci_access_port_to_interface_policy_leaf_profile:
      <<: *apic_info
      leaf_interface_profile: "{{apic_leaf_profile}}"
      access_port_selector: Port_Selector
      policy_group: Access_Port_Policy
      description: created by Ansible
      state: present        
 
  - name: Create a switch leaf profile 
    aci_switch_policy_leaf_profile:
      <<: *apic_info
      leaf_profile: SW_Leaf_101_102
      description: created by Ansible
      state: present        
    
  - name: Adding switch policy leaf profile selector associated Node Block range
    aci_switch_leaf_selector:
      <<: *apic_info
      leaf_profile: SW_Leaf_101_102
      leaf: node_101_102
      leaf_node_blk: L_101_102
      from: 101
      to: 102
      state: present

  - name: Associate interface selector profile to switch policy leaf profile 
    aci_interface_selector_to_switch_policy_leaf_profile:
      <<: *apic_info
      leaf_profile: "{{apic_leaf_profile}}"
      interface_selector: "{{apic_int_sel01}}"
      state: present  
 
  - name: Static path binding for given EPG 
    aci_static_binding_to_epg:
      <<: *apic_info
      tenant: "{{tenant}}"
      ap: "{{app_pr}}"
      epg: "{{apic_epg_01}}"  
      encap_id: 3001
      deploy_immediacy: lazy
      interface_mode: untagged
      interface_type: switch_port
      pod_id: 1
      leafs: 101
      interface: '1/41'  
      state: present
